export enum RuleName {
    Bingo = 'bingo',
    EndGame = 'endGame',
    PlacementMustBeValid = 'placementMustBeValid',
    MustFormValidWords = 'mustFormValidWords',
    MustKeepEaselFull = 'mustKeepEaselFull',
    MustFirstPlacementBeValid = 'mustFirstPlacementBeValid',
    ScoringNewWords = 'scoringNewWords',
    TradeLetterRule = 'tradeLetterRule',
    FormedWordOfLengthX = 'formedWordOfLengthX',
    RageTime = 'place one second before end of turn 3 times',
    ScoreOnePoint = 'score one point',
    LetterTrio = 'formed word contains 3 times a letter X',
    BonusMaster = 'activate X bonus tiles',
    QuickPlacement = 'place within 2 seconds',
    SkipTrade = 'skip then trade',
    Corner = 'place in a corner',
    MustSendGoals = 'must send goals',
}
